---
name: ci

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@6.0.0
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: windows-latest
    strategy:
      matrix:
        suite:
          - default
          - tools32
          - tools64
          - msys2-tools64
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Install Cinc Workstation
        uses: sous-chefs/.github/.github/actions/install-workstation@6.0.0
      - name: Test Kitchen
        run: kitchen test ${{ matrix.suite }}
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.exec.yml

  final:
    runs-on: ubuntu-latest
    needs: [integration]
    steps:
      - run: echo Done
